// src/fallback/spelling.rs portu
namespace NormalizerTr;

internal static class Spelling
{
    public static string? LetterName(int letter) => letter switch
    {
        'a' or 'A' => "a",
        'b' or 'B' => "be",
        'c' or 'C' => "ce",
        'ç' or 'Ç' => "çe",
        'd' or 'D' => "de",
        'e' or 'E' => "e",
        'f' or 'F' => "fe",
        'g' or 'G' => "ge",
        'ğ' or 'Ğ' => "yumuşak ge",
        'h' or 'H' => "he",
        'ı' or 'I' => "ı",
        'i' or 'İ' => "i",
        'j' or 'J' => "je",
        'k' or 'K' => "ke",
        'l' or 'L' => "le",
        'm' or 'M' => "me",
        'n' or 'N' => "ne",
        'o' or 'O' => "o",
        'ö' or 'Ö' => "ö",
        'p' or 'P' => "pe",
        'q' or 'Q' => "kü",
        'r' or 'R' => "re",
        's' or 'S' => "se",
        'ş' or 'Ş' => "şe",
        't' or 'T' => "te",
        'u' or 'U' => "u",
        'ü' or 'Ü' => "ü",
        'v' or 'V' => "ve",
        'w' or 'W' => "çift ve",
        'x' or 'X' => "iks",
        'y' or 'Y' => "ye",
        'z' or 'Z' => "ze",
        _ => null,
    };

    public static string? SymbolName(int symbol) => symbol switch
    {
        '.' => "nokta",
        ',' => "virgül",
        ':' => "iki nokta",
        ';' => "noktalı virgül",
        '/' => "eğik çizgi",
        '\\' => "ters eğik çizgi",
        '-' or '–' or '—' => "tire",
        '+' => "artı",
        '−' => "eksi",
        '=' => "eşittir",
        '×' => "çarpı işareti",
        '*' => "yıldız",
        '÷' => "bölme işareti",
        '%' => "yüzde",
        '&' => "ve",
        '@' => "et",
        '#' => "kare",
        '<' => "küçüktür işareti",
        '>' => "büyüktür işareti",
        '_' => "alt çizgi",
        '(' => "aç parantez",
        ')' => "kapat parantez",
        '[' => "aç köşeli parantez",
        ']' => "kapat köşeli parantez",
        '{' => "aç süslü parantez",
        '}' => "kapat süslü parantez",
        '\'' or '’' => "kesme",
        '"' or '“' or '”' => "tırnak",
        '!' => "ünlem",
        '?' => "soru işareti",
        '|' or '¦' => "dikey çizgi",
        '`' => "ters kesme",
        '~' => "tilde",
        '^' => "şapka işareti",
        '…' => "üç nokta",
        '°' => "derece işareti",
        '₺' => "Türk lirası işareti",
        '$' => "dolar işareti",
        '€' => "avro işareti",
        '£' => "sterlin işareti",
        '¥' => "yen işareti",
        '©' => "telif işareti",
        '®' => "tescilli marka işareti",
        '™' => "marka işareti",
        '•' or '·' or '◦' or '▪' => "nokta işareti",
        '→' or '⇒' => "sağ ok",
        '←' => "sol ok",
        '↑' => "yukarı ok",
        '↓' => "aşağı ok",
        '✓' or '✔' => "onay işareti",
        '★' or '☆' or '⭐' => "yıldız",
        '≈' => "yaklaşık işareti",
        '≠' => "eşit değil işareti",
        '≤' => "küçük eşit işareti",
        '≥' => "büyük eşit işareti",
        '±' => "artı eksi işareti",
        '∞' => "sonsuzluk işareti",
        '‰' => "binde işareti",
        '√' => "karekök işareti",
        'π' => "pi",
        0x1F642 => "gülümseyen yüz", // 🙂
        _ => null,
    };

    /// <summary>Ordinary prose punctuation is retained for sentence structure, not dropped.</summary>
    public static bool ProsePunctuation(int symbol) => symbol is '.' or ',' or ';' or ':' or '!' or '?' or '('
        or ')' or '[' or ']' or '{' or '}' or '"' or '\'' or '’' or '“' or '”' or '…' or '-' or '–' or '—';
}
